/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#ffdcd8",
        "surface-container-high": "#2a2a2a",
        "inverse-surface": "#e5e2e1",
        "on-secondary": "#690007",
        "on-surface-variant": "#c0c7d6",
        "on-tertiary": "#003822",
        "surface": "#131313",
        "outline": "#8a919f",
        "outline-variant": "#404754",
        "on-surface": "#e5e2e1",
        "surface-tint": "#a6c8ff",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#005234",
        "on-tertiary-fixed": "#002112",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed": "#001c3b",
        "primary-fixed-dim": "#a6c8ff",
        "secondary-fixed": "#ffdad6",
        "on-primary-fixed-variant": "#004786",
        "inverse-primary": "#005fb0",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "secondary-container": "#ce0018",
        "tertiary": "#00e297",
        "primary": "#a6c8ff",
        "primary-container": "#2992ff",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "on-primary-container": "#002a53",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#ffb4ac",
        "on-primary": "#00315f",
        "background": "#131313",
        "on-tertiary-container": "#00311d",
        "on-secondary-fixed": "#410002",
        "primary-fixed": "#d5e3ff",
        "surface-container": "#201f1f",
        "secondary": "#ffb4ac",
        "tertiary-fixed": "#4dffb2",
        "on-background": "#e5e2e1",
        "on-secondary-fixed-variant": "#93000e",
        "tertiary-fixed-dim": "#00e297",
        "surface-bright": "#3a3939",
        "tertiary-container": "#00a56d",
        "tesla-red": "#E82127",
        "electric-blue": "#008CFF",
        "success-green": "#00E599",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "grid-margin": "24px",
        xl: "32px",
        "grid-gutter": "20px",
        lg: "24px",
        md: "16px",
        sm: "12px",
        xs: "8px",
        base: "4px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
